# Generated by Django 3.1.4 on 2020-12-30 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('can_publish', 'Can Publish Posts'),)},
        ),
    ]
