# Generated by Django 3.1.4 on 2020-12-29 23:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201230_0455'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reasearcher',
            new_name='Researcher',
        ),
        migrations.AlterField(
            model_name='companyadmin',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='companyadmin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='companymod',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='companymod', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rootadmin',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rootadmin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rootmod',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rootmod', to=settings.AUTH_USER_MODEL),
        ),
    ]
