# Generated by Django 3.1.4 on 2020-12-30 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201230_0516'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='researcher',
            table='researcher',
        ),
    ]
